### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by haru-27** [haru-27/furima-35012#9]
# フリマアプリのURL
https://furima-35012.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin
パスワード: 2222

# 出品者用のメールアドレスとパスワード
メールアドレス: taro@example.com
パスワード: abc123

# 購入者用のメールアドレスとパスワード
メールアドレス: jiro@example.com
パスワード: abc123

**Comment by runak25033** [comment]
ご提出ありがとうございます.

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
<img width="916" alt="最終課題LGTM2" src="https://user-images.githubusercontent.com/79125420/112778385-65513800-907f-11eb-8db8-23b098605320.png">
